Few security fixes
brainstormforce/all-in-one-schemaorg-rich-snippets pull request #135
Opened 2023-02-08 11:01 UTC by mahajanleena1995

- Nonce verification in all the Reset options
- Check ABSPATH in index.php

2023-02-08 13:01 UTC, patilvikasj commented on admin/index.php
> +										' . wp_nonce_field( 'snippet_review_form_action', 'snippet_review_nonce_field' ) //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Remove PHPCS ignore and use escaping.

2023-02-08 13:01 UTC, patilvikasj commented on admin/index.php
> +										' . wp_nonce_field( 'snippet_event_form_action', 'snippet_event_nonce_field' ) //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Same here. Remove PHPCS ignore comment.

2023-02-08 13:04 UTC, patilvikasj requested changes
Please check comments @mahajanleena1995

2023-02-09 12:01 UTC, mahajanleena1995 commented on admin/index.php
> +										' . wp_nonce_field( 'snippet_review_form_action', 'snippet_review_nonce_field' ) //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Done

2023-02-09 12:01 UTC, mahajanleena1995 commented on admin/index.php
> +										' . wp_nonce_field( 'snippet_event_form_action', 'snippet_event_nonce_field' ) //phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped
Done

2023-02-09 13:19 UTC, patilvikasj approved these changes

2023-02-09 13:22 UTC, merged